---
abstract: 'Extend your attribute traits interface for Mouse'
author:
  - 'Nikolay Shulyakovskiy <n.shulyakovskiy@corp.mail.ru>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Mouse: v2.5.9
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.38, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MouseX-AttributeTraitHelper-Merge
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.010001'
resources:
  repository: https://github.com/my-mail-ru/MouseX-AttributeTraitHelper-Merge
version: '0.9'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
