---
abstract: 'Extend your attribute traits interface for Mouse'
author:
  - 'Nikolay Shulyakovskiy <n.shulyakovskiy@corp.mail.ru>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Mouse: v2.5.9
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MouseX-AttributeTraitHelper
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.010001'
resources:
  repository: https://gitlab.corp.mail.ru/mydev/mousex-attributetraithelper
version: '0.9'
